version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "clarityNotes-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hz4i99hvi9ug"
s3_prefix = "clarityNotes-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=271991961134.dkr.ecr.us-east-1.amazonaws.com/clarity-notes-sam"]
